# Generated by Django 5.2.4 on 2025-11-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0022_postransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefrosh',
            name='total_profit',
            field=models.PositiveIntegerField(default=0, verbose_name='سود فاکتور'),
        ),
    ]
