# Generated by Django 5.2.4 on 2025-11-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0023_invoicefrosh_total_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicefrosh',
            name='total_standard_price',
            field=models.PositiveIntegerField(default=0, verbose_name='مجموع قیمت معیار'),
        ),
    ]
