# Generated by Django 5.2.4 on 2025-11-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0024_invoicefrosh_total_standard_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdevice',
            name='account_number',
            field=models.CharField(max_length=50, verbose_name='شماره حساب'),
        ),
    ]
