# Generated by Django 5.2.4 on 2025-11-28 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0025_alter_posdevice_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ نقدی')),
                ('remaining_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ باقیمانده')),
                ('remaining_payment_method', models.CharField(choices=[('cash', 'نقدی'), ('pos', 'دستگاه پوز'), ('check', 'چک'), ('credit', 'نسیه')], default='pos', max_length=10, verbose_name='روش پرداخت باقیمانده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_payment', to='invoice_app.invoicefrosh')),
                ('pos_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.posdevice', verbose_name='دستگاه پوز برای باقیمانده')),
            ],
            options={
                'verbose_name': 'پرداخت نقدی',
                'verbose_name_plural': 'پرداخت\u200cهای نقدی',
            },
        ),
    ]
