# Generated by Django 5.2.4 on 2025-12-14 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0028_alter_inventorycount_profit_percentage'),
        ('cantact_app', '0010_branch_modem_ip'),
        ('invoice_app', '0026_cashpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مرجوعی')),
                ('total_return_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل مرجوعی')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='علت مرجوعی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
                ('original_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='invoice_app.invoicefrosh', verbose_name='فاکتور اصلی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر ثبت\u200cکننده')),
            ],
            options={
                'verbose_name': 'مرجوعی فاکتور',
                'verbose_name_plural': 'مرجوعی\u200cهای فاکتورها',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد مرجوعی')),
                ('original_quantity', models.PositiveIntegerField(verbose_name='تعداد اصلی')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت واحد')),
                ('total_price', models.PositiveIntegerField(verbose_name='قیمت کل مرجوعی')),
                ('standard_price', models.PositiveIntegerField(default=0, verbose_name='قیمت معیار')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='علت مرجوعی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.invoiceitemfrosh', verbose_name='آیتم اصلی فاکتور')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account_app.inventorycount', verbose_name='کالا')),
                ('return_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice_app.returninvoice', verbose_name='مرجوعی')),
            ],
            options={
                'verbose_name': 'آیتم مرجوعی',
                'verbose_name_plural': 'آیتم\u200cهای مرجوعی',
            },
        ),
    ]
