# Generated by Django 5.2.4 on 2025-12-14 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0027_returninvoice_returnitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='returninvoice',
            options={'ordering': ['-created_at'], 'verbose_name': 'مرجوعی فاکتور', 'verbose_name_plural': 'مرجوعی\u200cهای فاکتور'},
        ),
        migrations.RemoveField(
            model_name='returninvoice',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='returninvoice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='original_quantity',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='standard_price',
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید'),
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_returns', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده'),
        ),
        migrations.AddField(
            model_name='returninvoice',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مرجوعی'),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل مرجوعی'),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار تأیید'), ('approved', 'تأیید شده'), ('rejected', 'رد شده'), ('completed', 'تکمیل شده')], default='pending', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='returninvoice',
            name='total_return_amount',
            field=models.PositiveIntegerField(default=0, verbose_name='مبلغ مرجوعی'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='original_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoice_app.invoiceitemfrosh', verbose_name='آیتم اصلی'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='تعداد مرجوعی'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='دلیل مرجوعی آیتم'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='return_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice_app.returninvoice'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='total_price',
            field=models.PositiveIntegerField(verbose_name='مبلغ کل مرجوعی'),
        ),
    ]
