# Generated by Django 5.2.4 on 2025-12-14 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0028_alter_returninvoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='returnitem',
            name='return_invoice',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='original_item',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='product',
        ),
        migrations.CreateModel(
            name='ReturnLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ مرجوع')),
                ('return_profit', models.PositiveIntegerField(default=0, verbose_name='سود مرجوع')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='دلیل مرجوع')),
                ('return_data', models.JSONField(blank=True, null=True, verbose_name='داده\u200cهای مرجوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ مرجوع')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_logs', to='invoice_app.invoicefrosh', verbose_name='فاکتور')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مرجوع کننده')),
            ],
            options={
                'verbose_name': 'لاگ مرجوع',
                'verbose_name_plural': 'لاگ\u200cهای مرجوع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ReturnInvoice',
        ),
        migrations.DeleteModel(
            name='ReturnItem',
        ),
    ]
