# Generated by Django 5.2.4 on 2025-12-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0029_remove_returnitem_return_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paymentnumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دستگاه')),
                ('account_holder', models.CharField(max_length=100, verbose_name='نام صاحب حساب')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('account_number', models.CharField(max_length=50, verbose_name='شماره حساب')),
                ('bank_name', models.CharField(max_length=100, verbose_name='نام بانک')),
                ('ip_address', models.GenericIPAddressField(default='192.168.1.157', verbose_name='آدرس IP')),
                ('port', models.IntegerField(default=1362, verbose_name='پورت')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش فرض')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'دستگاه پوز',
                'verbose_name_plural': 'دستگاه\u200cهای پوز',
            },
        ),
    ]
