# Generated by Django 5.2.4 on 2025-12-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0030_paymentnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpayment',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='نهایی شده'),
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='نهایی شده'),
        ),
    ]
