# Generated by Django 5.2.4 on 2025-12-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0031_checkpayment_is_finalized_creditpayment_is_finalized'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpayment',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید'),
        ),
        migrations.AlterField(
            model_name='creditpayment',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید'),
        ),
        migrations.AlterField(
            model_name='invoicefrosh',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید'),
        ),
    ]
