# Generated by Django 5.2.4 on 2025-12-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_app', '0032_alter_checkpayment_is_finalized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicefrosh',
            name='created_at',
            field=models.DateTimeField(verbose_name='تاریخ ایجاد'),
        ),
    ]
