# Generated by Django 5.2.4 on 2025-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=100)),
                ('record_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('data', models.JSONField(blank=True, null=True)),
                ('sync_direction', models.CharField(choices=[('local_to_server', 'لوکال به سرور'), ('server_to_local', 'سرور به لوکال')], default='local_to_server', max_length=20)),
                ('sync_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_resolved', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('app_name', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('last_sync_timestamp', models.DateTimeField(blank=True, help_text='آخرین زمان سینک موفق', null=True)),
                ('batch_id', models.CharField(blank=True, help_text='شناسه دسته برای ردیابی', max_length=100)),
                ('is_full_sync', models.BooleanField(default=False, help_text='آیا سینک کامل بوده است؟')),
            ],
            options={
                'db_table': 'change_tracker',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sync_status', 'model_type'], name='change_trac_sync_st_be26bb_idx'), models.Index(fields=['app_name', 'model_name'], name='change_trac_app_nam_dcfb83_idx'), models.Index(fields=['created_at'], name='change_trac_created_ab2bce_idx'), models.Index(fields=['last_sync_timestamp', 'model_type'], name='change_trac_last_sy_2b2d72_idx'), models.Index(fields=['batch_id'], name='change_trac_batch_i_c603e6_idx')],
            },
        ),
    ]
