# Generated by Django 5.2.4 on 2025-11-06 04:21

from django.db import migrations



class Migration(migrations.Migration):

    dependencies = [
        ('sync_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='changetracker',
            new_name='sync_api_ch_sync_st_5a56c4_idx',
            old_name='change_trac_sync_st_be26bb_idx',
        ),
        migrations.RenameIndex(
            model_name='changetracker',
            new_name='sync_api_ch_app_nam_a83653_idx',
            old_name='change_trac_app_nam_dcfb83_idx',
        ),
        migrations.RenameIndex(
            model_name='changetracker',
            new_name='sync_api_ch_created_708b4e_idx',
            old_name='change_trac_created_ab2bce_idx',
        ),
        migrations.RenameIndex(
            model_name='changetracker',
            new_name='sync_api_ch_last_sy_992fd2_idx',
            old_name='change_trac_last_sy_2b2d72_idx',
        ),
        migrations.RenameIndex(
            model_name='changetracker',
            new_name='sync_api_ch_batch_i_cf47e0_idx',
            old_name='change_trac_batch_i_c603e6_idx',
        ),
        migrations.AlterModelTable(
            name='changetracker',
            table='sync_api_changetracker',
        ),
    ]
