# Generated by Django 5.2.4 on 2025-11-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sync_api', '0002_delete_serversynclog_delete_synctoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['app_name', 'model_name', 'is_synced'], name='sync_api_ch_app_nam_71676d_idx'), models.Index(fields=['changed_at'], name='sync_api_ch_changed_1d627c_idx')],
            },
        ),
    ]
