# Generated by Django 5.2.4 on 2025-11-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('data_type', models.CharField(choices=[('string', 'متنی'), ('integer', 'عددی'), ('boolean', 'بولین'), ('json', 'JSON')], default='string', max_length=20)),
            ],
            options={
                'verbose_name': 'تنظیمات آفلاین',
                'verbose_name_plural': 'تنظیمات آفلاین',
                'db_table': 'offline_settings',
            },
        ),
        migrations.CreateModel(
            name='SyncSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('records_synced', models.IntegerField(default=0)),
                ('records_total', models.IntegerField(default=0)),
                ('sync_direction', models.CharField(choices=[('local_to_server', 'لوکال به سرور'), ('server_to_local', 'سرور به لوکال')], max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('partial', 'ناقص')], default='in_progress', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('sync_type', models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی'), ('forced', 'اجباری')], default='auto', max_length=20)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sync_sessions',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='DataSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=100)),
                ('record_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('data', models.JSONField(blank=True, null=True)),
                ('sync_direction', models.CharField(choices=[('local_to_server', 'لوکال به سرور'), ('server_to_local', 'سرور به لوکال')], default='local_to_server', max_length=20)),
                ('sync_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('conflict_resolved', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('app_name', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('branch_id', models.IntegerField(blank=True, null=True)),
                ('last_sync_timestamp', models.DateTimeField(blank=True, help_text='آخرین زمان سینک موفق', null=True)),
                ('batch_id', models.CharField(blank=True, help_text='شناسه دسته برای ردیابی', max_length=100)),
                ('is_full_sync', models.BooleanField(default=False, help_text='آیا سینک کامل بوده است؟')),
            ],
            options={
                'db_table': 'data_sync_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sync_status', 'model_type'], name='data_sync_l_sync_st_da996f_idx'), models.Index(fields=['app_name', 'model_name'], name='data_sync_l_app_nam_823676_idx'), models.Index(fields=['created_at'], name='data_sync_l_created_58aa4f_idx'), models.Index(fields=['last_sync_timestamp', 'model_type'], name='data_sync_l_last_sy_c99b7c_idx'), models.Index(fields=['batch_id'], name='data_sync_l_batch_i_6bd50d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ServerSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=100)),
                ('record_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('data', models.JSONField()),
                ('source_ip', models.GenericIPAddressField()),
                ('sync_direction', models.CharField(choices=[('local_to_server', 'لوکال به سرور'), ('server_to_local', 'سرور به لوکال')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('app_name', models.CharField(blank=True, max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'server_sync_log',
                'indexes': [models.Index(fields=['processed', 'created_at'], name='server_sync_process_7f244c_idx')],
            },
        ),
    ]
