# Generated by Django 5.2.4 on 2025-11-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0005_datasynclog_batch_id_datasynclog_is_full_sync_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=50)),
                ('record_id', models.BigIntegerField()),
                ('action', models.CharField(max_length=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('is_synced', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['app_name', 'model_name', 'is_synced'], name='sync_app_ch_app_nam_6c4463_idx'), models.Index(fields=['changed_at'], name='sync_app_ch_changed_3b6b34_idx')],
            },
        ),
    ]
