# Generated by Django 5.2.4 on 2025-11-05 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sync_app', '0006_changetracker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangeTracker',
        ),
    ]
