# Generated by Django 5.2.4 on 2025-12-16 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cantact_app', '0010_branch_modem_ip'),
        ('invoice_app', '0029_remove_returnitem_return_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان هزینه')),
                ('expense_type', models.CharField(choices=[('operational', 'عملیاتی'), ('personnel', 'پرسنلی'), ('administrative', 'اداری'), ('other', 'متفرقه')], default='operational', max_length=20, verbose_name='نوع هزینه')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('expense_date', models.DateField(verbose_name='تاریخ هزینه')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('pos', 'دستگاه پوز'), ('check', 'چک'), ('credit', 'نسیه')], default='cash', max_length=10, verbose_name='روش پرداخت')),
                ('payment_status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expense_attachments/', verbose_name='ضمیمه')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_expenses', to='cantact_app.branch', verbose_name='شعبه')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
            ],
            options={
                'verbose_name': 'هزینه نقدی',
                'verbose_name_plural': 'هزینه\u200cهای نقدی',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscrepancyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_date', models.DateField(verbose_name='تاریخ مغایرت')),
                ('old_amount', models.PositiveIntegerField(verbose_name='مبلغ قبل از تغییر')),
                ('new_amount', models.PositiveIntegerField(verbose_name='مبلغ بعد از تغییر')),
                ('difference', models.IntegerField(default=0, verbose_name='مقدار تفاوت')),
                ('description', models.TextField(blank=True, verbose_name='دلیل مغایرت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی شده'), ('resolved', 'رفع شده')], default='pending', max_length=20, verbose_name='وضعیت بررسی')),
                ('review_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('review_notes', models.TextField(blank=True, verbose_name='یادداشت بررسی')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='یادداشت رفع مغایرت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantact_app.accuntmodel', verbose_name='سرمایه گذار')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discrepancy_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='بررسی کننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_creator', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
            ],
            options={
                'verbose_name': 'لاگ مغایرت',
                'verbose_name_plural': 'لاگ\u200cهای مغایرت',
                'ordering': ['-discrepancy_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ (تومان)')),
                ('investment_date', models.DateField(verbose_name='تاریخ سرمایه گذاری')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدی'), ('credit', 'حساب')], max_length=10, verbose_name='روش پرداخت')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investments', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='invoice_app.creditpayment', verbose_name='حساب اعتباری')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.accuntmodel', verbose_name='سرمایه گذار')),
            ],
            options={
                'verbose_name': 'سرمایه گذاری',
                'verbose_name_plural': 'سرمایه گذاری\u200cها',
                'ordering': ['-investment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_date', models.DateField(verbose_name='تاریخ موجودی')),
                ('inventory_type', models.CharField(choices=[('cash', 'نقدی'), ('account', 'حساب')], default='cash', max_length=10, verbose_name='نوع موجودی')),
                ('calculated_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ محاسبه شده')),
                ('actual_amount', models.PositiveIntegerField(default=0, verbose_name='مبلغ واقعی')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده')),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantact_app.accuntmodel', verbose_name='سرمایه گذار')),
            ],
            options={
                'verbose_name': 'موجودی صندوق',
                'verbose_name_plural': 'موجودی\u200cهای صندوق',
                'ordering': ['-inventory_date'],
                'unique_together': {('inventory_date', 'inventory_type', 'branch', 'investor')},
            },
        ),
    ]
