# Generated by Django 5.2.4 on 2025-12-17 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0010_branch_modem_ip'),
        ('cash_management', '0001_initial'),
        ('invoice_app', '0030_paymentnumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investment',
            options={'ordering': ['-created_at'], 'verbose_name': 'سرمایه\u200cگذاری', 'verbose_name_plural': 'سرمایه\u200cگذاری\u200cها'},
        ),
        migrations.RemoveField(
            model_name='investment',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='credit_account',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='notes',
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_letters',
            field=models.CharField(default=1, max_length=500, verbose_name='مبلغ به حروف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.paymentnumber', verbose_name='حساب بانکی'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_date',
            field=models.DateField(verbose_name='تاریخ سرمایه\u200cگذاری'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.accuntmodel', verbose_name='سرمایه\u200cگذار'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'واریز به حساب')], max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
