# Generated by Django 5.2.4 on 2025-12-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0002_alter_investment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='amount_letters',
        ),
        migrations.AddField(
            model_name='investment',
            name='amount_in_words',
            field=models.CharField(default=1, max_length=500, verbose_name='مبلغ به حروف'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('transfer', 'واریز به حساب')], max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
