# Generated by Django 5.2.4 on 2025-12-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0003_remove_investment_amount_letters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='amount_in_words',
            new_name='amount_letters',
        ),
        migrations.AlterField(
            model_name='investment',
            name='amount',
            field=models.BigIntegerField(verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدی'), ('bank_transfer', 'واریز به حساب')], max_length=20, verbose_name='روش پرداخت'),
        ),
    ]
