# Generated by Django 5.2.4 on 2025-12-21 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0004_rename_amount_in_words_investment_amount_letters_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cashinventory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cashinventory',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='cashinventory',
            name='confirmed_by',
        ),
        migrations.RemoveField(
            model_name='cashinventory',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='discrepancylog',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='discrepancylog',
            name='investor',
        ),
        migrations.RemoveField(
            model_name='discrepancylog',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='discrepancylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='CashExpense',
        ),
        migrations.DeleteModel(
            name='CashInventory',
        ),
        migrations.DeleteModel(
            name='DiscrepancyLog',
        ),
    ]
