# Generated by Django 5.2.4 on 2025-12-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_management', '0005_alter_cashinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_finalized',
            field=models.BooleanField(default=False, verbose_name='در انتظار تایید'),
        ),
    ]
