# Generated by Django 5.2.4 on 2025-12-22 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0010_branch_modem_ip'),
        ('cash_management', '0006_investment_is_finalized'),
        ('invoice_app', '0030_paymentnumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_date', models.DateField(verbose_name='تاریخ مغایرت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('previous_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ قبل از تغییر')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='مبلغ پس از تغییر')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='مبلغ تفاوت')),
                ('item_type', models.CharField(choices=[('invoice_cash', 'فاکتور نقدی'), ('invoice_pos', 'فاکتور پوز'), ('invoice_check', 'چک'), ('invoice_credit', 'نسیه'), ('investment', 'سرمایه\u200cگذاری')], max_length=20, verbose_name='نوع مورد')),
                ('item_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه مورد')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='توضیح مختصر')),
                ('reason', models.TextField(max_length=1000, verbose_name='علت مغایرت')),
                ('reviewer_melicode', models.CharField(max_length=10, verbose_name='کد ملی رسیدگی کننده')),
                ('responder_melicode', models.CharField(max_length=10, verbose_name='کد ملی پاسخ دهنده')),
                ('review_status', models.CharField(choices=[('pending', 'بررسی مجدد لازم'), ('reviewed_rejected', 'بررسی شد و تایید نشد'), ('reviewed_approved', 'بررسی شد و تایید شد')], default='pending', max_length=20, verbose_name='وضعیت بررسی')),
                ('resolution_status', models.CharField(choices=[('unresolved', 'رفع نشده'), ('resolved', 'رفع شده')], default='unresolved', max_length=20, verbose_name='وضعیت رفع مغایرت')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان رفع')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_discrepancies', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cash_management.investment', verbose_name='سرمایه\u200cگذاری مربوطه')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice_app.invoicefrosh', verbose_name='فاکتور مربوطه')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_discrepancies', to=settings.AUTH_USER_MODEL, verbose_name='بررسی کننده')),
            ],
            options={
                'verbose_name': 'مغایرت',
                'verbose_name_plural': 'مغایرت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
