# Generated by Django 5.2.4 on 2025-12-27 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantact_app', '0010_branch_modem_ip'),
        ('cash_management', '0008_dailycashstatus_dailycashadjustment_dailycheque_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discrepancy',
            name='notes',
            field=models.TextField(blank=True, verbose_name='یادداشت\u200cها'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='cash_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='cheque_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='credit_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='investment_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='pos_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
