# Generated by Django 5.2.4 on 2025-11-05 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0024_stocktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpricing',
            name='highest_purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='بالاترین قیمت خرید'),
        ),
    ]
