# Generated by Django 5.2.4 on 2025-11-28 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0025_alter_productpricing_highest_purchase_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelPrintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('barcode', models.CharField(max_length=100, verbose_name='بارکد')),
                ('branch_name', models.CharField(max_length=100, verbose_name='نام شعبه')),
                ('print_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ چاپ')),
                ('print_quantity', models.IntegerField(verbose_name='تعداد چاپ شده')),
                ('selling_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت فروش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر چاپ کننده')),
            ],
            options={
                'verbose_name': 'تاریخچه چاپ لیبل',
                'verbose_name_plural': 'تاریخچه\u200cهای چاپ لیبل',
                'ordering': ['-print_date'],
            },
        ),
    ]
