# Generated by Django 5.2.4 on 2025-11-28 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0026_labelprinthistory'),
        ('cantact_app', '0010_branch_modem_ip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLabelSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, verbose_name='نام کالا')),
                ('barcode', models.CharField(max_length=100, verbose_name='بارکد')),
                ('allow_print', models.BooleanField(default=True, verbose_name='اجازه چاپ')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantact_app.branch', verbose_name='شعبه')),
            ],
            options={
                'verbose_name': 'تنظیمات چاپ کالا',
                'verbose_name_plural': 'تنظیمات چاپ کالاها',
                'unique_together': {('product_name', 'branch')},
            },
        ),
        migrations.CreateModel(
            name='LabelPrintItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('print_quantity', models.IntegerField(verbose_name='تعداد چاپ شده')),
                ('print_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ چاپ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر چاپ کننده')),
                ('label_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_items', to='account_app.productlabelsetting', verbose_name='تنظیمات کالا')),
            ],
            options={
                'verbose_name': 'آیتم چاپ لیبل',
                'verbose_name_plural': 'آیتم\u200cهای چاپ لیبل',
                'ordering': ['-print_date'],
            },
        ),
        migrations.DeleteModel(
            name='LabelPrintHistory',
        ),
    ]
