# Generated by Django 5.2.4 on 2025-12-05 20:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0027_productlabelsetting_labelprintitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycount',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), max_digits=5, verbose_name='درصد سود'),
        ),
    ]
